project:
  type: website

website:
  title: "Spotify Songs 2023"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: histogram.qmd
        text: Distribution of BPM
      - href: key_mode.qmd
        text: Key Mode Frequency Heatmap
      - href: dance_ablility.qmd
        text: Dance Ability By Key
      - href: speech_histogram.qmd
        text: Speechiness Histogram
      - href: speech_vs_bpm.qmd
        text: Speech V.S BPM
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



