---
title: "Histogram"
author: "Shyamali Sheth"
execute:
    echo: false
    message: false
    warning: false

---



```{r}
#|label: setup
#|message: false

library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r}
#|label: loadingdata
#|message: false

data <- read_csv("data/spotify-2023.csv")
data <- data %>%
  rename(artist_name = `artist(s)_name`)

track_counts <- data %>%
  count(artist_name)
```

```{r}
#|label: histogram
#|message: false

data$bpm <- as.numeric(data$bpm)

ggplot(data, aes(x = bpm)) +
  geom_histogram(binwidth = 20, fill = "skyblue", color = "black") +
  geom_text(stat = 'bin', aes(label = ..count..), binwidth = 20, vjust = -0.5) +
#  theme_minimal() +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 15),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) +
  labs(title = "Distribution of BPM",
       subtitle = "Most Songs have beats between 100 - 150",
       x = "Beats per Minute",
       y = "Count of Somgs") +
  scale_x_continuous(labels = scales::label_comma())
```