---
title: "Speechiness Histogram"
author: "Shyamali Sheth"
execute:
  echo: false
  message: false
  warning: false

---

```{r}
#|label: setup
#|message: false

library(ggplot2)
library(dplyr)
library(tidyverse)
```

```{r}
#|label: loadingdata
#|message: false

data <- read_csv("data/spotify-2023.csv")
data <- data %>%
  rename(speechiness = `speechiness_%`)
```

```{r}
#| label:  speechinessHistogram

# Create a histogram with percentage labels
ggplot(data, aes(x = speechiness)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  geom_text(stat = 'bin', aes(label = ..count..), binwidth = 5, vjust = -0.5) +
  labs(title = "Distribution of Speechiness",
       subtitle = "Majority of songs have a speechiness score below 10",
       x = "Speechiness", y = "Count of Songs") +
  theme(plot.title = element_text(size = 20, face = "bold"),
        plot.subtitle = element_text(size = 15),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12))
```
